version: "3.9"

services:
  web-ui:
    build:
      context: .
      dockerfile: UI/Dockerfile
    depends_on:
      - add-service
      - sub-service
    restart: on-failure
  add-service:
    build:
        context: .
        dockerfile: AddService/Dockerfile
    
    restart: on-failure
  sub-service:
    build:
        context: .
        dockerfile: SubService/Dockerfile
   
    restart: on-failure
  seq:
    image: datalust/seq
    ports:
     - 5341:5341
     - 5342:80
    volumes:
     - rps_seq_data1:/data
    environment:
     - ACCEPT_EULA=Y
     
volumes:
 rps_seq_data1:
    


