
services:
  web-ui:
    build:
      context: .
      dockerfile: UI/Dockerfile
    depends_on:
      - adding-service
      - subing-service
    ports:
      - "8000:80"
    restart: on-failure
    
  adding-service:
    build:
        context: .
        dockerfile: AddService/Dockerfile
    deploy:
        replicas: 3
    restart: on-failure
    
  subing-service:
    build:
        context: .
        dockerfile: SubService/Dockerfile
    deploy:
        replicas: 3
    restart: on-failure
    
  seq:
    image: datalust/seq
    ports:
     - 5341:5341
     - 5342:80
    volumes:
     - rps_seq_data1:/data
    environment:
     - ACCEPT_EULA=Y
     
volumes:
 rps_seq_data1:
    


